### ISSUE TITLE
Mouser Project for UK/UE Rileylink

### ISSUE THREAD

**Issue by oskarpearson** [ps2/rileylink#34]
Hi

Attached is a Mouser project with enough components to make about 5 UK/EU Rilelylinks with a bunch of the cheap components spare (enough to lose / burn out / keep for later)

Note - it will _not_ work in the USA as I've changed the Balun and Antenna as described at https://github.com/ps2/rileylink/tree/master/hardware#868mhz-eu-version

I'm not 100% sure the components are all correct yet - but if they are, it should ease ordering for other people, since they don't have to select from 27,000+ capacitor models.. Feedback on my selections is welcome. My one concern is it seems some of the capacitors in the diagram are electrolytic - but I couldn't find electrolytic capacitors in those ranges. I also had to switch the LEDs, as I couldn't find the model referenced.

http://www.mouser.com/ProjectManager/ProjectDetail.aspx?AccessID=2316caefe4

Once I know this works, I'll submit a PR and update the BOM

Oskar

**Comment by ps2** [comment]
Thanks Oskar!

I built a list at digikey using the same components that I've used to build my own RileyLinks.  Might want to compare the capacitors and resistors.  There are only a few that require tight tolerances.  The led resistors and power filtering caps just have to be ballpark. 

https://www.digikey.com/classic/RegisteredUser/BOMBillOfMaterials.aspx?path=1&exist=1&id=2957565

This list also has "extra" parts for the 0402 size pieces, as those are super easy to lose.  Sometimes the extra amount is 10+, since it's cheaper to buy 10 than it is to buy 2 or 3.
